# SPDX-FileCopyrightText: 2021 - 2026
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Rubankumar Moorthy <r.moorthy@fz-juelich.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
# - Research Centre Juelich GmbH - Institute of Bio- and Geosciences Agrosphere (IBG-3, https://www.fz-juelich.de/en/ibg/ibg-3)
#
# SPDX-License-Identifier: EUPL-1.2

version: '3.3'

services:
  nginx:
    image: registry.hzdr.de/hub-terra/sms/orchestration/nginx:fzj-dev-latest
    restart: unless-stopped
    volumes:
      - /root/traefik-portainer-config/traefik/config/certs/server.pem:/etc/ssl/default.crt:ro
      - /root/traefik-portainer-config/traefik/config/certs/server.key:/etc/ssl/private/default.key:ro
      - /etc/ssl/dhparam.pem:/etc/ssl/dhparam.pem:ro
      - /root/traefik-portainer-config/traefik/config/certs/server.pem:/etc/ssl/chain.pem:ro
      - ibg3dev-backend-static-files:/usr/share/nginx/html/static/backend:ro
      - ibg3dev-idl-static-files:/usr/share/nginx/html/static/idl:ro
    networks:
      - reverseproxy
      - sms-dev-nginx-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sms-dev-nginx-net.rule=Host(`sms-dev.ibg3jucloud-intern.ibg.kfa-juelich.de`)"
      - "traefik.http.routers.sms-dev-nginx-net.entrypoints=websecure"
      - "traefik.http.services.sms-dev-nginx-net.loadbalancer.server.port=90"
      - "traefik.http.routers.sms-dev-nginx-net.service=sms-dev-nginx-net"
      - "traefik.http.routers.sms-dev-nginx-net.tls=true"
      - "traefik.docker.network=reverseproxy"

  ibg3dev-idl:
    image: registry.hzdr.de/hub-terra/sms/gfz-idl/backend:latest
    restart: unless-stopped
    environment:
      DJANGO_DEBUG: 'False'
      DJANGO_ALLOWED_HOSTS: 'sms-dev.ibg3jucloud-intern.ibg.kfa-juelich.de ibg3dev-idl'
      DJANGO_CSRF_TRUSTED_ORIGINS: 'https://sms-dev.ibg3jucloud-intern.ibg.kfa-juelich.de'
      DJANGO_BASE_PATH: idl/
      DJANGO_STATIC_URL: /static/idl/
      DJANGO_STATIC_ROOT: /static/idl/
      DJANGO_DB_ENGINE: django.db.backends.postgresql
      DJANGO_DB_NAME: idl
      DJANGO_DB_USER: $IDL_DB_USER
      DJANGO_DB_PASSWORD: $IDL_DB_PASSWORD
      DJANGO_DB_HOST: ibg3dev-idl-db
      DJANGO_DB_PORT: 5432
      IDL_TOKEN: $SMS_IDL_TOKEN
      OIDC_WELL_KNOWN_URL: https://login.helmholtz.de/oauth2/.well-known/openid-configuration
      VO_ADMIN_CONVENTIONS: '*:fzj-sms-admin'
      VO_MEMBER_CONVENTIONS: '*:fzj-sms-member'
    volumes:
      - ibg3dev-idl-static-files:/static/idl
    networks:
      - sms-dev-nginx-net
      - ibg3dev-idl-db

  ibg3dev-idl-db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $IDL_DB_PASSWORD
      POSTGRES_USER: $IDL_DB_USER
      POSTGRES_DB: idl
    volumes:
      - "ibg3dev-idl-db-data:/var/lib/postgresql/data"
    shm_size: 128M
    networks:
      - ibg3dev-idl-db

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ibg3dev-elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - ibg3dev-backend

  ibg3dev-minio:
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    restart: unless-stopped
    volumes:
      - ibg3dev-minio-data:/data/minio
    networks:
      - sms-dev-nginx-net
      - ibg3dev-backend
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    #      To deactivate the console
    #      MINIO_BROWSER: "off"
    command: server /data/minio --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://ibg3dev-minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  ibg3dev-backend-db:
    image: postgis/postgis:12-3.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $BACKEND_DB_PASSWORD
      POSTGRES_USER: $BACKEND_DB_USER
      POSTGRES_DB: backend
    volumes:
      - "ibg3dev-backend-db-data:/var/lib/postgresql/data"
    shm_size: 128M
    networks:
      - ibg3dev-backend

  ibg3dev-backend:
    image: registry.hzdr.de/hub-terra/sms/orchestration/backend:fzj-dev-latest 
    restart: unless-stopped
    environment:
      URL_PREFIX: /backend/api/v1
      STATIC_URL: /static/backend
      APP_SETTINGS: project.config.ProductionConfig
      DATABASE_URL: postgresql://${BACKEND_DB_USER}:${BACKEND_DB_PASSWORD}@ibg3dev-backend-db:5432/backend
      OIDC_USERNAME_CLAIM: eduperson_principal_name
      WELL_KNOWN_URL: https://login.helmholtz.de/oauth2/.well-known/openid-configuration
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: sms-attachments
      MINIO_ENDPOINT: ibg3dev-minio:9000
      DOWNLOAD_ENDPOINT: https://sms-dev.ibg3jucloud-intern.ibg.kfa-juelich.de/
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      ALLOWED_MIME_TYPES: ${ALLOWED_MIME_TYPES}
      ELASTICSEARCH_URL: http://elastic-search:9200
      HTTP_ORIGINS: ${HTTP_ORIGINS}
      SMS_IDL_TOKEN: $SMS_IDL_TOKEN
      IDL_URL: http://ibg3dev-idl:8000/idl/api/idl
      CV_URL: https://sms-cv.helmholtz.cloud/sms/cv/api/v1
      SMS_BACKEND_URL: /backend/api/v1
      PKCE_CLIENT_ID: sms_ibg3_fzj
      PKCE_SCOPES: profile openid email eduperson_principal_name
      INSTITUTE: fzj
      SMS_FRONTEND_URL: https://sms-dev.ibg3jucloud-intern.ibg.kfa-juelich.de/
      SMS_VERSION: ${SMS_VERSION}
      TSMDL_API_URL: https://decoupling-api.ibg3container.ibg.kfa-juelich.de/tsmdl/api/v1
      TSM_ENDPOINTS: '[{"fields": {"name": "FZJ", "url": "https://decoupling-api.ibg3container.ibg.kfa-juelich.de/tsmdl/api/v1"}, "model": "TsmEndpoint", "pk": 3}]'
      B2INST_TOKEN: ${B2INST_TOKEN}
      B2INST_URL: https://b2inst-test.gwdg.de
      B2INST_COMMUNITY: DataHub-Helmholtz-RF-EE
      PID_SERVICE_URL: https://rz-vm561.gfz.de:8000/api/handles
      PID_SERVICE_USER: ${PID_SERVICE_USER}
      PID_SERVICE_PASSWORD: ${PID_SERVICE_PASSWORD}
      PID_PREFIX: 20.500.14372
      PID_SUFFIX: SMS-Dev
      CLIENT_ID: sms_ibg3_fzj

    depends_on:
      - ibg3dev-backend-db
    volumes:
      - ibg3dev-backend-static-files:/usr/src/app/project/static
    networks:
      - ibg3dev-backend
      - sms-dev-nginx-net

volumes:
  ibg3dev-idl-db-data:
  ibg3dev-idl-static-files:
  ibg3dev-elasticsearch-data:
  ibg3dev-minio-data:
  ibg3dev-backend-db-data:
  ibg3dev-backend-static-files:
networks:
  sms-dev-nginx-net:
  ibg3dev-backend:
  ibg3dev-idl-db:
  reverseproxy:
    external: true
